pollon/pages/urls.py
from django.urls import path
from . import views
app_name= 'pages'
urlpatterns=[
    path('',views.index,name="index")
]

pollon/pollon/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.views.static import serve
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls), 
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollon/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns=[
    path('',views.index,name="index"),
    path('<str:question_id>/',views.details,name="details"),
    path('results/<str:question_id>/',views.results,name="results"),
    path('<str:question_id>/vote/',views.vote,name="vote"),
    path('resultsdata/<str:question_id>',views.resultsData,name="resultsData"),
    path('add',views.addPoll,name="addPoll"),

]

pollon/pages/models.py
from django.db import models

# Create your models here.

pollon/polls/models.py
from django.db import models
import datetime
from . import helpers
# Create your models here.
class Question(models.Model):
    question_text = models.TextField(max_length=400)
    pub_date = models.DateTimeField('Date Published',default=datetime.datetime.now())
    open_for_all = models.BooleanField(default=True)
    def __str__(self):
        return self.question_text
    def link(self):
        return helpers.inttohex(self.id) 

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return  self.choice_text

pollon/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'pages/index.html')

pollon/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import Http404,HttpResponseRedirect,JsonResponse,HttpResponse
from django.urls import reverse
from django import forms
from . import helpers

# Create your views here.
from .models import Question , Choice


##Model Form
class Get_Question(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text','open_for_all']
        widgets = {
          'question_text': forms.Textarea(attrs={'rows':4, 'cols':15}),
        }
     
class Get_Choices(forms.Form):
    choice = forms.CharField(label="Enter A Choice Seperated By ';' ",widget=forms.Textarea(attrs={'rows':2, 'cols':15}))
    

#Get Quesitons
def index(request):
    latest_question = Question.objects.order_by('-pub_date').filter(open_for_all=True)
    return render(request,"polls/index.html",{
        'latest_question' : latest_question
    })

#Get Details For A Poll
def details(request,question_id):
    qid= helpers.hextoint(question_id)
    try:
        question = Question.objects.get(pk=int(qid))
    except Question.DoesNotExist:
        raise Http404("Question Dies Not Exist")
    return render(request,"polls/details.html",{
        'question':question
    })

#Get Results For A Poll
def results(request,question_id):
    qid= helpers.hextoint(question_id)
    question =  get_object_or_404(Question,pk=int(qid))
    return render(request,'polls/results.html',{
        'question':question
    })

#Vote For A Poll
def vote(request,question_id):
    qid= helpers.hextoint(question_id)

    question = get_object_or_404(Question,pk=qid)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request,"polls/details.html",{
            'question':question,
            "error":"You Didn't Select A Choice",
        
        })
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(question_id,)))

#Return A Chart
def resultsData(request,question_id):
    qid= helpers.hextoint(question_id)
    votes=[]
    question = Question.objects.get(pk=question_id)
    choices = question.choice_set.all()
    for i in choices:
        votes.append({
            i.choice_text:i.votes
        })
    return JsonResponse(votes,safe=False)

#Add A Poll
def addPoll(request):
    if request.method == 'POST':
        choices=[]
        q_form = Get_Question(request.POST,prefix='question')
        c_form = Get_Choices(request.POST,prefix='choice')
        if(c_form.is_valid() and q_form.is_valid()):
            question = q_form.save()
            print(question)
            qid = question.link()
            # qid= helpers.hextoint(ques) 
            data = c_form.cleaned_data["choice"]
            choices =data.split(";")
            print(choices)
            for choice in choices:
                ch = Choice(choice_text=choice,question=question)
                ch.save()
            print(q_form.cleaned_data)

        return render(request,"polls/addPoll.html",{
            "q_form": q_form,
            "c_form": c_form,
            'submitted':True,
            "qid":qid
        })
    else:
        c_form = Get_Choices(prefix="choice")
        q_form = Get_Question(prefix='question')
        return render(request,"polls/addPoll.html",{
            "q_form": q_form,
            "c_form": c_form,
            'submitted':False,
        })

pollon/pages/templates/pages/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'pages/home.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600&display=swap" rel="stylesheet">
    <title>Pollon</title>
</head>
<body>
    <div class="jumbotron">
        <div class="heading">Pollon - Want a poll? We got you.</div>
        <div class="split">
            <div class="left">
                <div class="link">
                <a href="{% url 'polls:addPoll' %}" class="jumbotron-text">Create A Poll</a>

                </div>
            </div>
            <div class="right">
                <div class="link">
                <a href="{% url 'polls:index' %}" class="jumbotron-text">See Existing Polls</a>

                </div>
            </div>
        </div>
        <div class="footer">
            Made With Love For <strong>Who Wants To Be A Hackionaire?</strong>
        </div>
    </div>
</body>
</html>

pollon/polls/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
<div class="container">
    <div class="navbar-brand"> <a href="{% url 'pages:index' %}" style="color: white;text-decoration: none; font-weight: 800; letter-spacing: 2px; font-size: 1.5rem;"> Pollon</a></div>
</div>
 <div class="navbar-nav">
      <a class="nav-item nav-link active mr-4 font-weight-bold" href="{% url 'polls:addPoll' %}">Add A Poll<span class="sr-only">(current)</span></a>
    </div>
</nav>

pollon/polls/templates/polls/addPoll.html
{% extends 'polls/layout.html' %}
{% block body %}
{% load crispy_forms_tags %}
<style>
    h1,h3{
        text-align: center;
    }
    input[type='text'],textarea{
        display: block;
    }
    textarea{
        width: 100%;
        border-radius: 5px;
        margin-bottom: 10px;
    }
</style>
 
    <h1 class="heading-1 align-center">Add Question</h1>
    <form class="form mb-4" action="{% url 'polls:addPoll' %}" method="POST">
        {%csrf_token%}
        {{q_form|crispy}}
        <br>
        <br>
        <h3 class="heading-1 align-center">Choices</h3>
        {{c_form}}
        {% if not submitted %}
        <input class="btn btn-success btn-large" type="submit" name="submit" id="submit" value="Create">
        {% else %}
        <input class="btn btn-info btn-large" disabled name="submit" id="submit" value="Created">
        {% endif %}
    </form>
    <div class="mt-3" style="text-align: center;">
    {% if qid %}
    <input type="text" value="{{request.get_host}}/polls/{{qid}}" id="myInput" class="form-control mb-2" disabled >
    <button class="btn btn-outline-success mt-2" id="copyButton">Copy Link</button>
    {% endif %}
    </div>

<script>
    window.onload = () => {
         function myCopy() {
  var copyText = document.getElementById("myInput");

  copyText.select();
  copyText.setSelectionRange(0, 99999); /* For mobile devices */

  document.execCommand("copy");

}
    const btn = document.getElementById('copyButton')
    btn.addEventListener('click',() => myCopy)
   }
</script>
    
{% endblock %}

pollon/polls/templates/polls/details.html
{% extends 'polls/layout.html' %}
{% block body %}

<form action="{% url 'polls:vote' question.link %}" method="post">
    <p class="lead" style="font-weight: 600;">
       Q.  {{question}}
</p>
<br>
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <div class="form-check">
            <input type="radio" name="choice" class="form-check-input" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label class="form-check-label" for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
        </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4">
</form>
{% endblock %}

pollon/polls/templates/polls/index.html
{% extends 'polls/layout.html' %}

{% block body %}
<h1 class="display-4">Active Polls</h1>
{% for question in latest_question %}
<div class="card mb-3">
    <div class="card-body">
        <p class="lead">
{{question}}
        </p>
        <a href="{% url 'polls:details' question.link %}" class="btn btn-primary btn-sm">Vote Now</a>
        <a href="{% url 'polls:results' question.link %}" class="btn btn-secondary btn-sm">Results</a>
    </div>
</div> 
{% empty %}
    NO POLLS
{% endfor %}

<br>
<a class="btn btn-outline-primary mb-4 mt-4" href="{% url 'polls:addPoll' %}"> Add A Poll </a>
{% endblock %}

pollon/polls/templates/polls/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polls/layout.css' %}">
    <title>Pollon</title>
    <style>
    body {
	background: #ecf0f1;
    }
    .navbar {
	    background-color: #3498db !important;
    }

    </style>
</head>
<body>
    {% include 'partials/_navbar.html' %}
    <div class="container">
        <div class="col-md-9 col-sm-12 m-auto">
    {% block body %}
    {% endblock %}
        </div>
    </div>
</body>
</html>

pollon/polls/templates/polls/results.html
{% extends 'polls/layout.html' %}

{% block body %}
<script src="https://cdn.zingchart.com/zingchart.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<ul class="list-group mb-5">
        <p class="lead" style="font-weight: 600;">
       Q.  {{question}}
</p>
<br>
<br>
<br>
<br>
    {% for choice in question.choice_set.all %}
    
    <li class="list-group-item">
        {{choice.choice_text }} <span class="badge badge-success float-right">
            {{choice.votes}} vote{{choice.votes | pluralize}}
        </span>
    </li>
    {% empty %}
    No Results Found
    {% endfor %}
    
</ul>
<div id="myChart"></div>
<a href="{% url 'polls:index' %}" class="btn btn-secondary mt-4 mb-4">Back To Polls</a>

<script>
    var state = {
        "items":[],
        "values":[],
    }
    var question_id = "{{question.id}}"
    // var dataURL = `/polls/resultsData/${question_id}/` 
    dataURL="{% url 'polls:resultsData' question.id %}"
    $.ajax({
    method:'GET',
    url:dataURL,
    success:function(response){
        console.log("Response",response)
        for(var i in response){
            var key = Object.keys(response[i])[0]
            var value = Object.values(response[i])[0]
            state.items.push(key)
            state.values.push(value)
        }
        buildChart()
        // console.log(state)
    }
    })

    function buildChart(){
        var chartData = {
        "type":"bar",
        "scale-x":{
            "values":state.items
        },
        "series":[
            {
                "values":state.values
            }
        ]
    }

        zingchart.render({
            id:"myChart",
            data:chartData
        })

    
    }

    
</script>

{% endblock %}